version: "3"

services:
  api_toche_web:
    build: .
    restart: on-failure
    ports:
      - 9006:8080
    volumes:
      - /toche_api/files:/files

networks:
  default:
    external:
      name: mysql-network