version: "3"

services:
  api_toche_web:
    build:
      context: .
      args:
        deployTime: "${DEPLOYTIME}"
    restart: on-failure
    ports:
      - 9006:8080

networks:
  default:
    external:
      name: mysql-network