spring:
  profiles:
    group:
      "local": "local"
      "real": "real"

  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
