spring:
  profiles:
    group:
      "local": "local"
      "real": "real"

  jpa:
    properties:
      hibernate:
        format_sql: true
    open-in-view: false # open in view false

logging:
  level:
    org:
      hibernate:
        SQL: debug

management:
  endpoints:
    web:
      base-path: /serverStatus

