spring:
  profiles:
    group:
      "local": "local"
      "real": "real"

  jpa:
    properties:
      hibernate:
        format_sql: true
    open-in-view: false # open in view false

  batch:
    jdbc:
      initialize-schema: NEVER
    job:
      names: ${job.name:NONE}
      enabled: false # 배치 자동실행 막기

logging:
  level:
    org:
      hibernate:
        SQL: debug

management:
  endpoints:
    web:
      base-path: /serverStatus

