spring:
  profiles:
    group:
      "local": "local,private"
      "real": "real,private"

  jpa:
    properties:
      hibernate:
        format_sql: true
    open-in-view: false # open in view false

  batch:
    jdbc:
      initialize-schema: NEVER
    job:
      names: ${job.name:NONE}
      enabled: false # 배치 자동실행 막기

logging:
  level:
    org:
      hibernate:
        SQL: debug

management:
  endpoints:
    web:
      base-path: /serverStatus

riotApi:
  path:
    ranker: https://kr.api.riotgames.com/tft/league/v1/
    summonerDetail: https://kr.api.riotgames.com/tft/summoner/v1/summoners/