spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/toche;MODE=MySQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
  quartz:
    auto-startup: false

path.setPatch: /Users/heekng/heekngCoding/api_toche_web_setPatch/