spring:
  profiles:
    group:
      "local": "local,private"
      "real": "real,private"

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    #        show_sql: true
    open-in-view: false # open in view false

  batch:
    jdbc:
      initialize-schema: NEVER
    job:
      names: ${job.name:NONE}
      enabled: false # 배치 자동실행 막기

  datasource:
    hikari:
      maximum-pool-size: 30
logging:
  level:
    org:
      hibernate:
        SQL: debug
#        type: trace

management:
  endpoints:
    web:
      base-path: /serverStatus

riotApi:
  path:
    ranker: https://kr.api.riotgames.com/tft/league/v1/
    summonerDetail: https://kr.api.riotgames.com/tft/summoner/v1/summoners/
    matches: https://asia.api.riotgames.com/tft/match/v1/matches/by-puuid/
    matcheDetail: https://asia.api.riotgames.com/tft/match/v1/matches/
cdragon:
  path:
    tftLastJson: https://raw.communitydragon.org/latest/cdragon/tft/ko_kr.json
    tftLastJsonEn: https://raw.communitydragon.org/latest/cdragon/tft/en_us.json
    image: https://raw.communitydragon.org/latest/game/